[project]

name = "Pandora"
version = "0.1.0"
requires-python="==3.11.9"

dependencies = [
    "requests"
]
# IMP ref https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout
[tool.setuptools]
py-modules = []